Make start and end date configurable
rancherlabs/support-tools pull request #202
Opened 2022-12-05 04:54 UTC by masap

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

2022-12-21 10:56 UTC, leodotcloud requested changes

2022-12-21 10:56 UTC, leodotcloud commented on collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
> +      techo "Logging since ${OPTARG}"
```suggestion
      techo "Collecting logs starting ${OPTARG}"
```

2022-12-21 10:56 UTC, leodotcloud commented on collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
> +      techo "Logging until ${OPTARG}"
```suggestion
      techo "Collecting logs until ${OPTARG}"
```

2022-12-22 01:20 UTC, masap commented on collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
> +      techo "Logging since ${OPTARG}"
Thank you, fixed.

2022-12-22 01:20 UTC, masap commented on collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
> +      techo "Logging until ${OPTARG}"
Thank you, fixed.

2022-12-22 07:58 UTC, leodotcloud approved these changes

2022-12-22 07:58 UTC, merged