Adding sed to redact Rancher agent token
rancherlabs/support-tools pull request #53
Opened 2020-08-24 06:34 UTC by mattmattox

Adding `sed 's/token.*/token REDACTED/g'` in-order to redact the Rancher agent token for the Rancher agent logs.

2020-09-15 03:08 UTC, dkeightley commented on collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
> +    docker logs $SINCE_FLAG -t $RANCHERAGENT | sed 's/token.*/token REDACTED/g' > $TMPDIR/rancher/containerlogs/agent-$RANCHERAGENT 2>&1
The pipe will pass stdout by default, combining the streams before the pipe should ensure both get to `sed` and the log file.

The shorthand `|&` could also be used, but for consistency `2>&1`.

```suggestion
    docker logs $SINCE_FLAG -t $RANCHERAGENT 2>&1 | sed 's/token.*/token REDACTED/g' > $TMPDIR/rancher/containerlogs/agent-$RANCHERAGENT 2>&1
```

2020-09-15 03:10 UTC, dkeightley requested changes
Added one suggestion to ensure we catch the stderr output as well, otherwise LGTM!

2020-09-16 19:53 UTC, mattmattox commented
@dkeightley It should be fixed now.

2020-09-21 00:51 UTC, dkeightley approved these changes

2020-09-21 00:51 UTC, merged