Update link in README to contain branch in the URL
rancherlabs/support-tools pull request #60
Opened 2020-09-21 00:42 UTC by dkeightley

2020-10-07 13:13 UTC, mattmattox requested changes
Are we going to be changing to main instead of master or are we staying with master?

2020-11-04 19:39 UTC, dkeightley commented
Hi @mattmattox, we have a number of links using the master branch so it might be best to keep it consistent, any thoughts?

2020-11-24 19:11 UTC, mattmattox approved these changes

2020-11-24 20:31 UTC, dkeightley commented
Oops, just noticed this link had already been updated in the current README https://github.com/rancherlabs/support-tools/pull/69

2020-11-24 20:31 UTC, closed without merging